name: format and lint by biome

on:
  push:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 9.1.1

      # pnpm iを実行
      - run: pnpm i --frozen-lockfile

      # biomeによるフォーマットとlintを実行
      - run: pnpm check
